Windows support: added building and testing github actions

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -56,95 +56,86 @@ jobs:
         path: luac.cross
 
 
-  build_luac_cross_win:
+  build_win:
+    runs-on: windows-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - lua_ver: 51
+            numbers: float
+          - lua_ver: 51
+            numbers: integral
+          - lua_ver: 53
+            numbers: float
+          - lua_ver: 53
+            numbers: 64bit
 
-    runs-on: windows-2019
+    env:
+      LUA: ${{ matrix.lua_ver }}
+      MSYSTEM: MINGW32
+      CHERE_INVOKING: 1
 
     steps:
     - uses: actions/checkout@v4
       with:
         submodules: true
-    - name: Build luac.cross.exe
+
+    - uses: msys2/setup-msys2@v2
+      with:
+        update: true
+        cache: true
+        install: >-
+          make
+          gcc
+          python
+          python-pip
+          unzip
+
+    - name: Setup Python venv
+      shell: msys2 {0}
       run: |
-        set
-        "%programfiles%\git\usr\bin\xargs"
-        cd msvc
-        "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=Release /p:Platform=x64
-        mv luac-cross/x64/Release/luac.cross.exe ..
-      shell: cmd
+        python -m venv .venv
+        . .venv/bin/activate
+        python -m pip install --upgrade pip
+        pip install pyserial
+
+    - name: Build firmware
+      shell: msys2 {0}
+      run: |
+        . .venv/bin/activate
+
+        EXTRA_FLAGS=""
+        if [ "${{ matrix.numbers }}" = "integral" ]; then
+          EXTRA_FLAGS="-DLUA_NUMBER_INTEGRAL"
+        elif [ "${{ matrix.numbers }}" = "64bit" ]; then
+          EXTRA_FLAGS="-DLUA_NUMBER_64BITS"
+        fi
+        make EXTRA_CCFLAGS=$EXTRA_FLAGS
+        
+        if [ "${{ matrix.numbers }}" = "integral" ]; then
+          mv -f luac.cross.int.exe luac.cross.exe
+        fi
+
+    - name: Copy required DLLs
+      shell: msys2 {0}
+      run: |
+        ldd luac.cross.exe | awk '{print $3}' | grep -vi "/c/windows" | xargs -I{} cp -v {} . || true
+        ls *.dll
+
+    - name: Check build items
+      shell: msys2 {0}
+      run: |
+        ls -ll bin/0x00000.bin bin/0x10000.bin luac.cross.exe
+
     - name: Upload luac.cross
       if: ${{ success() }}
       uses: actions/upload-artifact@v4
       with:
-        name: luac.cross_51_float_win
-        path: luac.cross.exe
-
-
-  compile_lua:
-
-    strategy:
-      fail-fast: false
-      matrix:
-        lua_ver: [51, 53]
-        numbers: ['float']
-        filter: [ 'cat' ]
-        include:
-          - lua_ver: 51
-            numbers: 'integral'
-            filter: 'grep -v "lua_modules/lm92/lm92.lua\|lua_modules/hdc1000/HDC1000.lua\|lua_examples/u8g2/graphics_test.lua"'  
-          - lua_ver: 53
-            numbers: '64bit'  
-            filter: 'cat'
-    needs: build
-    runs-on: ubuntu-22.04
-
-    steps:
-    - name: Checkout repo
-      uses: actions/checkout@v4
-      with:
-        submodules: false
-    - name: Download luac.cross
-      uses: actions/download-artifact@v4
-      with:
-        name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}
-        path: ./
-    - name: Fix file permission
-      run: chmod +x luac.cross
-    - name: compile Lua
-      run: |
-        find lua_modules lua_examples tests/NTest* -iname "*.lua" | ${{ matrix.filter }} | xargs --delimiter="\n" echo
-        find lua_modules lua_examples tests/NTest* -iname "*.lua" | ${{ matrix.filter }} | xargs --delimiter="\n" ./luac.cross -p
-      shell: bash
-
-
-  compile_lua_win:
-
-    strategy:
-      fail-fast: false
-      matrix:
-        lua_ver: [51]
-        numbers: ['float']
-        filter: [ 'cat' ]
-    needs: build_luac_cross_win
-    runs-on: windows-latest
-
-    steps:
-    - name: Checkout repo
-      uses: actions/checkout@v4
-      with:
-        submodules: false
-    - name: Download luac.cross
-      uses: actions/download-artifact@v4
-      with:
         name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}_win
-        path: ./
-    - name: compile Lua
-      run: |
-        PATH="/C/Program\ Files/Git/usr/bin:${PATH}"
-        find lua_modules lua_examples tests/NTest* -iname "*.lua" | ${{ matrix.filter }} | xargs --delimiter="\n" echo
-        find lua_modules lua_examples tests/NTest* -iname "*.lua" | ${{ matrix.filter }} | xargs --delimiter="\n" ./luac.cross -p
-      shell: bash
-
+        path: |
+          luac.cross.exe
+          *.dll
 
   NTest:
 
@@ -193,10 +184,21 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        lua_ver: [51]
-        numbers: ['float']
-    needs: build_luac_cross_win
+        include:
+          - lua_ver: 51
+            numbers: 'float'
+          - lua_ver: 53
+            numbers: 'float'
+          - lua_ver: 51
+            numbers: 'integral'  
+          - lua_ver: 53
+            numbers: '64bit'  
+
+    needs: build_win
     runs-on: windows-latest
+    env:
+      MSYSTEM: MINGW32
+      CHERE_INVOKING: 1
 
     steps:
     - name: Checkout repo
@@ -212,15 +214,19 @@ jobs:
       run: |
         cd tests/NTest
         ../../luac.cross.exe -e ../NTest/NTest_NTest.lua | tee log
-        grep "failed. 0" log
-      shell: bash
+        if ((gc log | Select-String "failed: 0") -eq $null) { 
+          Throw "Errors were found during tests";
+        }
+      shell: pwsh
+        
     - name: NTest hosttests
       run: |
         cd tests
         cp NTest/NTest.lua .
         ../luac.cross.exe -e NTest_lua.lua | tee log
-        (if grep  " ==>  " log ; then exit 1 ; fi)
-      shell: bash
+        if ((gc log | Select-String " ==>  ") -ne $null) { 
+          Throw "Errors were found during tests";
+        }
 
 
   luacheck:
