Windows support: added building and testing github actions

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -59,95 +59,86 @@ jobs:
 # Sample job (that failed): https://github.com/nodemcu/nodemcu-firmware/actions/runs/17306868602/job/49131917376#step:3:153
 # => disable the Windows jobs for now
 
-  # build_luac_cross_win:
-
-  #   runs-on: windows-2022
-
-  #   steps:
-  #   - uses: actions/checkout@v4
-  #     with:
-  #       submodules: true
-  #   - name: Build luac.cross.exe
-  #     run: |
-  #       set
-  #       "C:\msys64\usr\bin\xargs.exe"
-  #       cd msvc
-  #       "%programfiles%\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" /p:Configuration=Release /p:Platform=x64
-  #       mv luac-cross/x64/Release/luac.cross.exe ..
-  #     shell: cmd
-  #   - name: Upload luac.cross
-  #     if: ${{ success() }}
-  #     uses: actions/upload-artifact@v4
-  #     with:
-  #       name: luac.cross_51_float_win
-  #       path: luac.cross.exe
-
-
-  compile_lua:
-
+  build_win:
+    runs-on: windows-latest
     strategy:
       fail-fast: false
       matrix:
-        lua_ver: [51, 53]
-        numbers: ['float']
-        filter: [ 'cat' ]
         include:
           - lua_ver: 51
-            numbers: 'integral'
-            filter: 'grep -v "lua_modules/lm92/lm92.lua\|lua_modules/hdc1000/HDC1000.lua\|lua_examples/u8g2/graphics_test.lua"'  
+            numbers: float
+          - lua_ver: 51
+            numbers: integral
           - lua_ver: 53
-            numbers: '64bit'  
-            filter: 'cat'
-    needs: build
-    runs-on: ubuntu-22.04
+            numbers: float
+          - lua_ver: 53
+            numbers: 64bit
+
+    env:
+      LUA: ${{ matrix.lua_ver }}
+      MSYSTEM: MINGW32
+      CHERE_INVOKING: 1
 
     steps:
-    - name: Checkout repo
-      uses: actions/checkout@v4
+    - uses: actions/checkout@v4
       with:
-        submodules: false
-    - name: Download luac.cross
-      uses: actions/download-artifact@v4
+        submodules: true
+
+    - uses: msys2/setup-msys2@v2
       with:
-        name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}
-        path: ./
-    - name: Fix file permission
-      run: chmod +x luac.cross
-    - name: compile Lua
+        update: true
+        cache: true
+        install: >-
+          make
+          gcc
+          python
+          python-pip
+          unzip
+
+    - name: Setup Python venv
+      shell: msys2 {0}
       run: |
-        find lua_modules lua_examples tests/NTest* -iname "*.lua" | ${{ matrix.filter }} | xargs --delimiter="\n" echo
-        find lua_modules lua_examples tests/NTest* -iname "*.lua" | ${{ matrix.filter }} | xargs --delimiter="\n" ./luac.cross -p
-      shell: bash
+        python -m venv .venv
+        . .venv/bin/activate
+        python -m pip install --upgrade pip
+        pip install pyserial
 
+    - name: Build firmware
+      shell: msys2 {0}
+      run: |
+        . .venv/bin/activate
 
-  # compile_lua_win:
+        EXTRA_FLAGS=""
+        if [ "${{ matrix.numbers }}" = "integral" ]; then
+          EXTRA_FLAGS="-DLUA_NUMBER_INTEGRAL"
+        elif [ "${{ matrix.numbers }}" = "64bit" ]; then
+          EXTRA_FLAGS="-DLUA_NUMBER_64BITS"
+        fi
+        make EXTRA_CCFLAGS=$EXTRA_FLAGS
+        
+        if [ "${{ matrix.numbers }}" = "integral" ]; then
+          mv -f luac.cross.int.exe luac.cross.exe
+        fi
 
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       lua_ver: [51]
-  #       numbers: ['float']
-  #       filter: [ 'cat' ]
-  #   needs: build_luac_cross_win
-  #   runs-on: windows-latest
+    - name: Copy required DLLs
+      shell: msys2 {0}
+      run: |
+        ldd luac.cross.exe | awk '{print $3}' | grep -vi "/c/windows" | xargs -I{} cp -v {} . || true
+        ls *.dll
 
-  #   steps:
-  #   - name: Checkout repo
-  #     uses: actions/checkout@v4
-  #     with:
-  #       submodules: false
-  #   - name: Download luac.cross
-  #     uses: actions/download-artifact@v4
-  #     with:
-  #       name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}_win
-  #       path: ./
-  #   - name: compile Lua
-  #     run: |
-  #       PATH="/C/Program\ Files/Git/usr/bin:${PATH}"
-  #       find lua_modules lua_examples tests/NTest* -iname "*.lua" | ${{ matrix.filter }} | xargs --delimiter="\n" echo
-  #       find lua_modules lua_examples tests/NTest* -iname "*.lua" | ${{ matrix.filter }} | xargs --delimiter="\n" ./luac.cross -p
-  #     shell: bash
+    - name: Check build items
+      shell: msys2 {0}
+      run: |
+        ls -ll bin/0x00000.bin bin/0x10000.bin luac.cross.exe
 
+    - name: Upload luac.cross
+      if: ${{ success() }}
+      uses: actions/upload-artifact@v4
+      with:
+        name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}_win
+        path: |
+          luac.cross.exe
+          *.dll
 
   NTest:
 
@@ -191,39 +182,54 @@ jobs:
       shell: bash
 
 
-  # NTest_win:
+  NTest_win:
 
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       lua_ver: [51]
-  #       numbers: ['float']
-  #   needs: build_luac_cross_win
-  #   runs-on: windows-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - lua_ver: 51
+            numbers: 'float'
+          - lua_ver: 53
+            numbers: 'float'
+          - lua_ver: 51
+            numbers: 'integral'  
+          - lua_ver: 53
+            numbers: '64bit'  
 
-  #   steps:
-  #   - name: Checkout repo
-  #     uses: actions/checkout@v4
-  #     with:
-  #       submodules: false
-  #   - name: Download luac.cross
-  #     uses: actions/download-artifact@v4
-  #     with:
-  #       name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}_win
-  #       path: ./
-  #   - name: NTest selfcheck
-  #     run: |
-  #       cd tests/NTest
-  #       ../../luac.cross.exe -e ../NTest/NTest_NTest.lua | tee log
-  #       grep "failed. 0" log
-  #     shell: bash
-  #   - name: NTest hosttests
-  #     run: |
-  #       cd tests
-  #       cp NTest/NTest.lua .
-  #       ../luac.cross.exe -e NTest_lua.lua | tee log
-  #       (if grep  " ==>  " log ; then exit 1 ; fi)
-  #     shell: bash
+    needs: build_win
+    runs-on: windows-latest
+    env:
+      MSYSTEM: MINGW32
+      CHERE_INVOKING: 1
+
+    steps:
+    - name: Checkout repo
+      uses: actions/checkout@v4
+      with:
+        submodules: false
+    - name: Download luac.cross
+      uses: actions/download-artifact@v4
+      with:
+        name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}_win
+        path: ./
+    - name: NTest selfcheck
+      run: |
+        cd tests/NTest
+        ../../luac.cross.exe -e ../NTest/NTest_NTest.lua | tee log
+        if ((gc log | Select-String "failed: 0") -eq $null) { 
+          Throw "Errors were found during tests";
+        }
+      shell: pwsh
+        
+    - name: NTest hosttests
+      run: |
+        cd tests
+        cp NTest/NTest.lua .
+        ../luac.cross.exe -e NTest_lua.lua | tee log
+        if ((gc log | Select-String " ==>  ") -ne $null) { 
+          Throw "Errors were found during tests";
+        }
 
 
   luacheck:
